services:
  devcontainer:
    build: 
      context: .
    network_mode: service:db
    command: sleep infinity

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
